<?php

class OperacionReal extends Operacion
{
    public function __construct(string $cadena)
    {
        parent::__construct($cadena);
    }

    public function calcula()
    {
        switch ($this->operador) {
            case '+':
                $resultado = $this->op1 + $this->op2;
                break;
            case '-':
                $resultado = $this->op1 - $this->op2;
                break;
            case '*':
                $resultado = $this->op1 * $this->op2;
                break;
            case '/':
                $resultado = $this->op1 / $this->op2;
                break;
        }
        return $resultado;

        }

        public function __toString()
        {
            $msj ="Soy una operacion Real";
            $msj .= parent::__toString(); // TODO: Change the autogenerated stub
            $msj .= $this->calcula();
            return $msj;
        }


}